# Generated by Django 2.0.6 on 2018-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_senddata_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='senddata',
            name='sample_chapter',
            field=models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/$D/'),
        ),
    ]
