# Generated by Django 2.0.6 on 2018-08-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_senddata_sample_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senddata',
            name='sample_chapter',
        ),
    ]
