# Generated by Django 2.0.6 on 2018-09-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_senddata_sample_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senddata',
            old_name='full_name',
            new_name='Job_title',
        ),
        migrations.RemoveField(
            model_name='senddata',
            name='phone_number',
        ),
    ]
