# Generated by Django 2.0.6 on 2018-09-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='empemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
