# Generated by Django 2.0.6 on 2018-09-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_document_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='empemail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
