# Generated by Django 2.0.6 on 2018-09-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180910_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='empemail',
            field=models.EmailField(max_length=254),
        ),
    ]
