# Generated by Django 2.0.6 on 2018-12-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_first_photo_slider_homeproject_homeslider_industry_ournews_projectstatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='industry',
        ),
    ]
